language: erlang

env:
  - LUA="luajit"
  - TESTS="database"
  - TESTS="promises"

install:
  - sudo apt-get update
  - sudo apt-get install -y luajit
  - sudo apt-get install -y luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

script:
  - busted -c -p TESTS tests

after_success:
  - 'egrep "./$TESTS.lua" luacov_report.txt | sed -n ''s/.*\s\([0-9.]\+%\).*/Code Coverage: \1/p'''
