language: erlang

env:
  - LUA="luajit"

install:
  - sudo apt-get update
  - sudo apt-get install -y luajit
  - sudo apt-get install -y luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

script:
  - busted -c tests
